version: '3'
services:
  web:
    build:
      # Specify workdir
      context: .
      dockerfile: Dockerfile.dev
    image: irishman/react-web
    ports:
      - '3000:3000'
    # Volumes to map folders from local machine to container
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]